/*
 * Renders the HTML sources in this folder into the committed rasters in
 * public/:
 *
 *   design/og/card.html              -> public/og.png               (1200x630)
 *   design/og/apple-touch-icon.html  -> public/apple-touch-icon.png (180x180)
 *
 *   node design/og/build.mjs
 *
 * Not part of the Vite build. Both are committed assets, regenerated by hand
 * when the copy, the palette or the mark changes — which is also why they can
 * depend on a locally installed browser and a locally installed Arial without
 * that becoming a deploy-time requirement. See card.html for why the font has
 * to come from the machine rather than from the repo.
 *
 * The newsletter site has the same script at the same path, rendering the same
 * card design; it has only one job there, because Next generates its
 * apple-touch-icon at build time from app/apple-icon.tsx. Keep the two in step
 * where they overlap.
 *
 * No npm dependency on purpose: this shells out to the browser that is already
 * on the machine. Puppeteer would pull a second Chromium down for one
 * screenshot a month.
 */
import { spawnSync } from "node:child_process";
import { existsSync, renameSync, rmSync, mkdtempSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, dirname, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const publicDir = resolve(here, "..", "..", "public");

const JOBS = [
  { src: "card.html", out: "og.png", width: 1200, height: 630 },
  {
    src: "apple-touch-icon.html",
    out: "apple-touch-icon.png",
    width: 180,
    height: 180,
  },
];

const CANDIDATES = [
  "C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe",
  "C:/Program Files/Microsoft/Edge/Application/msedge.exe",
  "C:/Program Files/Google/Chrome/Application/chrome.exe",
  "C:/Program Files (x86)/Google/Chrome/Application/chrome.exe",
];

const browser = CANDIDATES.find((path) => existsSync(path));

if (!browser) {
  console.error(
    "No Edge or Chrome found. Add the path to CANDIDATES in this file.",
  );
  process.exit(1);
}

/* Chromium's --screenshot needs an absolute path and will not tell you it
   wrote nothing, so each job renders into a scratch dir and the result is
   moved into place only once it exists. A failed render then leaves the
   previous asset untouched rather than deleting it. */
const scratch = mkdtempSync(join(tmpdir(), "navody-og-"));
let failed = false;

for (const job of JOBS) {
  const shot = join(scratch, job.out);
  const result = spawnSync(
    browser,
    [
      "--headless=new",
      "--disable-gpu",
      "--hide-scrollbars",
      /* Exactly the target size. No device-scale-factor: the text is
         rasterised at this size, not upscaled to it, so 1x is already sharp
         and 2x would only quadruple the bytes every scraper has to fetch. */
      `--window-size=${job.width},${job.height}`,
      /* These two cards are type only and need no local assets, but the flag
         stays so dropping an image into one later does not fail for a
         non-obvious reason: Chromium treats a file:// page reading a sibling
         file as cross-origin and blocks it by default. */
      "--allow-file-access-from-files",
      `--screenshot=${shot}`,
      pathToFileURL(resolve(here, job.src)).href,
    ],
    { stdio: "inherit" },
  );

  if (result.status !== 0 || !existsSync(shot)) {
    console.error(`Render failed for ${job.src} — public/${job.out} left as it was.`);
    failed = true;
    continue;
  }

  renameSync(shot, join(publicDir, job.out));
  console.log(`Wrote public/${job.out}`);
}

rmSync(scratch, { recursive: true, force: true });
process.exit(failed ? 1 : 0);
